spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  application:
    name: ex-beginner
server:
  servlet:
    context-path: /ex-beginner